import test from 'node:test';
import assert from 'node:assert/strict';
import { AudioControl, AudioControlError } from '../server/audio-control.mjs';
function adapter({ ready = true, awake = true, moves = [], blockedReason = null } = {}) { return { origin: 'http://reachy.local', config: { robotUrl: 'http://reachy.local/' }, snapshot: async () => ({ connected: true, ready, awake, moves, blockedReason }) }; }
function transport(responses = {}) { const calls = []; return { calls, request: async call => { calls.push(call); const response = responses[call.path]; if (response instanceof Error) throw response; return typeof response === 'function' ? response(call) : response; } }; }
test('status coalesces guarded bounded volume reads', async () => { let release, reads = 0; const t = transport({ '/api/volume/current': async () => { reads++; await new Promise(resolve => { release = resolve; }); return { volume: 37 }; } }); const audio = new AudioControl({ adapter: adapter(), transport: t.request }); const first = audio.status(), second = audio.status(); await new Promise(resolve => setImmediate(resolve)); assert.equal(reads, 1); release(); assert.deepEqual(await first, { available: true, speakerVolume: 37 }); assert.deepEqual(await second, { available: true, speakerVolume: 37 }); });
test('speaker volume is integer bounded and sends the fixed audited body', async () => { const t = transport({ '/api/volume/set': { volume: 66 } }); const audio = new AudioControl({ adapter: adapter(), transport: t.request }); for (const volume of [-1, 101, 1.5, NaN, '10', null]) await assert.rejects(audio.command({ action: 'speaker-volume', volume }), AudioControlError); await audio.command({ action: 'speaker-volume', volume: 66 }); assert.deepEqual(t.calls.map(({ path, method, body }) => ({ path, method, body })), [{ path: '/api/volume/set', method: 'POST', body: { volume: 66 } }]); });
test('guard receives action, permits declared own motion, and fallback speaker test requires awake', async () => { const t = transport({ '/api/volume/test-sound': { status: 'ok', message: 'played' } }); await assert.rejects(new AudioControl({ adapter: adapter({ moves: [{ uuid: 'foreign' }] }), transport: t.request }).command({ action: 'speaker-test' }), /no running motion/); let guarded; const audio = new AudioControl({ adapter: adapter({ moves: [{ uuid: 'owned' }] }), transport: t.request, guard: async action => { guarded = action; return action === 'speaker-test'; } }); assert.equal((await audio.command({ action: 'speaker-test' })).ok, true); assert.equal(guarded, 'speaker-test'); await assert.rejects(new AudioControl({ adapter: adapter({ awake: false }), transport: t.request }).command({ action: 'speaker-test' }), /Wake/); });
test('talk start has no hardware POST and fallback guard denies foreign motion or sleep', async () => { const t = transport(); await assert.rejects(new AudioControl({ adapter: adapter({ moves: [{ uuid: 'foreign' }] }), transport: t.request }).command({ action: 'talk-start' }), /no running motion/); await assert.rejects(new AudioControl({ adapter: adapter({ awake: false }), transport: t.request }).command({ action: 'talk-start' }), /Wake/); assert.deepEqual(await new AudioControl({ adapter: adapter(), transport: t.request }).command({ action: 'talk-start' }), { ok: true }); assert.equal(t.calls.length, 0); });test('busy/failure are audio-only and no status or mutation replay occurs', async () => { const base = adapter(); base.uncertain = null; const t = transport({ '/api/volume/test-sound': { status: 'busy', message: 'speaker in use' }, '/api/volume/current': new Error('offline') }); const audio = new AudioControl({ adapter: base, transport: t.request }); assert.equal((await audio.command({ action: 'speaker-test' })).ok, false); assert.equal(base.uncertain, null); assert.deepEqual(await audio.status(), { available: false, speakerVolume: 50, error: 'Audio request failed for /api/volume/current: offline' }); assert.equal(t.calls.filter(call => call.path === '/api/volume/test-sound').length, 1); });
test('Stop drains delayed accepted volume and speaker-test requests before stop and clear', async () => {
  for (const [action, route, response] of [
    [{ action: 'speaker-volume', volume: 42 }, '/api/volume/set', { volume: 42 }],
    [{ action: 'speaker-test' }, '/api/volume/test-sound', { status: 'ok', message: 'played' }],
  ]) {
    let release;
    const t = transport({ [route]: async () => { await new Promise(resolve => { release = resolve; }); return response; }, '/api/media/stop_sound': { status: 'ok' }, '/api/media/clear_incoming_audio': { status: 'ok' } });
    const audio = new AudioControl({ adapter: adapter(), transport: t.request });
    const earlier = audio.command(action); await new Promise(resolve => setImmediate(resolve));
    const stopping = audio.command({ action: 'audio-stop' }); await new Promise(resolve => setImmediate(resolve));
    assert.deepEqual(t.calls.map(call => call.path), [route], 'Stop cannot overtake an accepted audio effect');
    release(); await earlier; await stopping;
    assert.deepEqual(t.calls.map(call => call.path), [route, '/api/media/stop_sound', '/api/media/clear_incoming_audio']);
  }
});test('audio clear is distinct; stop orders stop_sound before clear and exposes no arbitrary routes', async () => { const t = transport({ '/api/media/stop_sound': { status: 'ok' }, '/api/media/clear_incoming_audio': { status: 'ok' } }); const audio = new AudioControl({ adapter: adapter(), transport: t.request }); await assert.rejects(audio.command({ action: 'anything', path: '/api/media/play_sound' }), /Unknown/); await audio.command({ action: 'audio-clear' }); await audio.command({ action: 'audio-stop', path: '/api/media/play_sound' }); assert.deepEqual(t.calls.map(({ path, method, body }) => ({ path, method, body })), [{ path: '/api/media/clear_incoming_audio', method: 'POST', body: undefined }, { path: '/api/media/stop_sound', method: 'POST', body: undefined }, { path: '/api/media/clear_incoming_audio', method: 'POST', body: undefined }]); });
test('demo never reads a robot and models test, stop and clear separately', async () => { const audio = new AudioControl({ adapter: { snapshot: async () => { throw Error('must not read robot'); } }, demo: true }); await audio.command({ action: 'speaker-volume', volume: 20 }); await audio.command({ action: 'speaker-test' }); await audio.command({ action: 'audio-stop' }); await audio.command({ action: 'audio-clear' }); assert.deepEqual(await audio.status(), { available: true, speakerVolume: 20 }); assert.deepEqual({ test: audio.testCount, stop: audio.stopCount, clear: audio.clearCount }, { test: 2, stop: 1, clear: 2 }); });